[toolchain]

[features]
resolution = true
skip-lint = false


[programs.localnet]
promise_keeper = "ARKDUPvSk7fVmY676dLctbqDfncxy6SPiTVhy8zJabCC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
